from _case_factory import case as C

LOGGED_IN = "Logged in on staging with EnvConfig inventory agent (PDV) after PIN validation"
CS = "On Customer Services with an eligible customer MSISDN"


def saa_918():
    j = "SAA-918"
    reqs = [
        {"id": "REQ-001", "testable": True},
        {"id": "REQ-002", "testable": True},
        {"id": "REQ-003", "testable": True},
        {"id": "REQ-004", "testable": True},
        {"id": "REQ-005", "testable": True},
        {"id": "REQ-006", "testable": True},
        {"id": "REQ-007", "testable": True},
        {"id": "REQ-008", "testable": True},
        {"id": "REQ-009", "testable": True},
        {"id": "REQ-010", "testable": True},
        {"id": "REQ-011", "testable": True},
        {"id": "REQ-012", "testable": True},
        {"id": "REQ-013", "testable": True},
        {"id": "REQ-014", "testable": True},
        {"id": "REQ-015", "testable": True},
        {"id": "REQ-016", "testable": True},
        {"id": "REQ-017", "testable": True},
        {"id": "REQ-018", "testable": True},
        {"id": "REQ-019", "testable": True},
        {"id": "REQ-020", "testable": True},
        {"id": "REQ-021", "testable": False},
        {"id": "REQ-022", "testable": True},
    ]
    cases = [
        C(j, 1, "SIM Swap", "User selects SIM Swap from Customer Services",
          LOGGED_IN, "1. Open Customer Services. 2. Select SIM Swap.",
          "SIM Swap flow starts. Allowed profiles in the ticket: POA, Dealer Shop, Team Leader, Staff. PDV may not be authorised; record if the action is hidden.",
          ["REQ-001"], "Step 1: Select SIM Swap", "Candidate", "positive"),
        C(j, 2, "SIM Swap", "MFS balance below 2,000 FCFA allows SIM Swap",
          CS + "; customer MFS balance 1,999 FCFA",
          "1. Continue past balance check.",
          "SIM Swap is allowed. Maximum allowed balance is 1,999 FCFA.",
          ["REQ-002"], "MFS Balance < 2,000 FCFA", "Manual", "boundary"),
        C(j, 3, "SIM Swap", "MFS balance 2,000 FCFA or more blocks with the quoted message",
          CS + "; customer MFS balance 2,000 FCFA",
          "1. Continue past balance check.",
          'SIM Swap is blocked. Message: "Sim swap not authorised. Please redirect customer to the nearest store."',
          ["REQ-003"], "Balance ≥ 2,000 FCFA", "Manual", "negative"),
        C(j, 4, "SIM Swap", "Regular is the default SIM Swap type",
          "Balance check passed",
          "1. Observe SIM Swap type.",
          "Options are Regular (Default) and Procuration.",
          ["REQ-004"], "Step 3: Select SIM Swap Type", "Manual", "positive", "Medium"),
        C(j, 5, "SIM Swap", "Procuration captures the procuration document",
          "Procuration selected",
          "1. Continue without the procuration document. 2. Upload it.",
          "FE captures procuration document. IsProcuration=1 on the request (backend evidence).",
          ["REQ-005"], "Procuration Rules", "Manual", "positive"),
        C(j, 6, "SIM Swap", "Supported ID types are offered",
          "On ID type selection",
          "1. Observe ID types.",
          "National ID Card, Foreign Passport, CEDEAO Card, Refugee Card are available.",
          ["REQ-006"], "Step 4: Select ID Type", "Manual", "positive", "Medium"),
        C(j, 7, "SIM Swap", "OCR extracts name, DOB, ID number; failure requires retake; OCR data not editable",
          "ID scan step",
          "1. Scan front and back where applicable. 2. Force an OCR failure. 3. Attempt to edit OCR fields.",
          "OCR extracts First Name, Last Name, Date of Birth, ID Number. On failure the user must retake. User cannot manually edit OCR data.",
          ["REQ-007", "REQ-008"], "Step 5: Scan Customer ID", "Manual", "negative"),
        C(j, 8, "SIM Swap", "Unsupported document is blocked",
          "An unsupported document",
          "1. Scan it.",
          "Error is shown. Transaction is blocked. Exact message is not quoted.",
          ["REQ-009"], "Unsupported Document", "Manual", "negative"),
        C(j, 9, "SIM Swap", "KYC First Name, Last Name, Date of Birth, ID Number are all required",
          "On KYC verification",
          "1. Leave each mandatory field empty in turn.",
          "All four fields required. Incomplete mandatory fields cannot continue.",
          ["REQ-010", "REQ-022"], "Step 6: Verify KYC Information", "Manual", "negative"),
        C(j, 10, "SIM Swap", "Successful identity comparison proceeds to SIM scan",
          "OCR data matches customer record on First Name, Last Name, Date of Birth, National ID Number",
          "1. Confirm verification.",
          "Verification successful. Flow proceeds to SIM scan.",
          ["REQ-011"], "Verification Successful", "Manual", "positive"),
        C(j, 11, "SIM Swap", "Failed verification shows the quoted message",
          "OCR data does not match the customer record",
          "1. Confirm verification.",
          'Message: "Identification failed. We were unable to verify customer identity."',
          ["REQ-012"], "Verification Failed", "Manual", "negative"),
        C(j, 12, "SIM Swap", "Failed verification without re-identification rights shows Cancel and Try Again",
          "Agent not authorised for Re-identification; verification failed",
          "1. Observe buttons.",
          "Buttons: Cancel, Try Again.",
          ["REQ-013"], "User not authorised for Re-identification", "Manual", "other"),
        C(j, 13, "SIM Swap", "Failed verification with re-identification rights offers Re-identify Customer",
          "Agent authorised for Re-identification; verification failed",
          "1. Observe buttons. 2. Tap Re-identify Customer.",
          "Buttons: Cancel, Try Again, Re-identify Customer. For Senegal, redirect to SIM Swap Uncertified Customer Flow.",
          ["REQ-014"], "User authorised for Re-identification", "Manual", "other"),
        C(j, 14, "SIM Swap", "Non-certified customer may need habit questionnaire and extra documents",
          "Eligible non-certified customer",
          "1. Continue SIM Swap.",
          "Identification may require Habit Questionnaire and Additional Documents. Service is allowed only if customer status is eligible.",
          ["REQ-015"], "Non-Certified Customer Rules", "Manual", "other", "Medium"),
        C(j, 15, "SIM Swap", "Burnt SIM / unreadable ICCID shows the quoted error",
          "On SIM scan; ICCID not readable",
          "1. Scan or enter an unreadable ICCID.",
          'Message: "Sim deactivated. Please scan another sim." Options: Try Again, Cancel.',
          ["REQ-016"], "Burnt SIM / ICCID Not Readable", "Manual", "negative"),
        C(j, 16, "SIM Swap", "ICCID already activated shows the quoted error",
          "Already activated ICCID",
          "1. Scan or enter it.",
          'Message: "Sim already registered. Please scan another sim." Options: Try Again, Cancel.',
          ["REQ-017"], "ICCID Already Activated", "Manual", "negative"),
        C(j, 17, "SIM Swap", "User can scan barcode or enter ICCID manually",
          "On SIM scan",
          "1. Scan barcode. 2. Enter ICCID manually on another attempt.",
          "Both scan ICCID and enter ICCID manually are available. Supported scan method is Barcode.",
          ["REQ-018"], "SIM Scan and ICCID Validation", "Manual", "positive", "Medium"),
        C(j, 18, "SIM Swap", "PIN completes swap; receipt fields and actions",
          "All prior steps successful",
          "1. Enter PIN. 2. Observe receipt. 3. Download. 4. Share.",
          "New SIM is activated and ICCID updated. Receipt: Certification Status = Certified, SIM Activation Status = Sim Activated, Customer Identity Verified, Transaction ID. Download Receipt and Share Receipt are available.",
          ["REQ-019", "REQ-020"], "SIM Swap Completion / Receipt", "Manual", "positive"),
        C(j, 19, "SIM Swap", "Regular vs Procuration attachments",
          "One Regular and one Procuration swap",
          "1. Complete attachments for each type.",
          "Regular: ID Front and ID Back if applicable. Procuration: ID documents plus procuration document.",
          ["REQ-005", "REQ-006"], "Attachment Requirements", "Manual", "other", "Medium"),
        C(j, 20, "SIM Swap", "Anti-fraud repeated ID rule has no expected result",
          "Same ID used in 3 SIM swap attempts the same day on different MSISDNs with different identities",
          "1. Perform the third attempt.",
          "Cannot be expected-resulted. The Expected Result heading under Anti-Fraud Validation is empty.",
          ["REQ-021"], "Anti-Fraud Validation", "Manual", "other", blocked=True),
    ]
    return reqs, cases


def saa_919():
    j = "SAA-919"
    reqs = [
        {"id": "REQ-001", "testable": True},
        {"id": "REQ-002", "testable": True},
        {"id": "REQ-003", "testable": True},
        {"id": "REQ-004", "testable": True},
        {"id": "REQ-005", "testable": True},
        {"id": "REQ-006", "testable": True},
        {"id": "REQ-007", "testable": True},
        {"id": "REQ-008", "testable": True},
        {"id": "REQ-009", "testable": True},
        {"id": "REQ-010", "testable": True},
        {"id": "REQ-011", "testable": True},
        {"id": "REQ-012", "testable": True},
        {"id": "REQ-013", "testable": True},
        {"id": "REQ-014", "testable": True},
        {"id": "REQ-015", "testable": True},
        {"id": "REQ-016", "testable": True},
        {"id": "REQ-017", "testable": True},
        {"id": "REQ-018", "testable": True},
    ]
    cases = [
        C(j, 1, "Upgrade Customer File", "User selects Upgrade Customer File from Customer Services",
          LOGGED_IN, "1. Open Customer Services. 2. Select Upgrade Customer File.",
          "Upgrade flow starts. Profiles in the ticket: Freelancer, POA, Cash Point, Dealer Shop, Team Leader.",
          ["REQ-001"], "Step 1", "Candidate", "positive"),
        C(j, 2, "Upgrade Customer File", "Only uncertified or rejected files can be upgraded",
          "Uncertified or rejected customer; agent authorised; MSISDN active",
          "1. Open Upgrade Customer File for that MSISDN.",
          "Upgrade is allowed.",
          ["REQ-002"], "Upgrade Eligibility — Allowed", "Manual", "positive"),
        C(j, 3, "Upgrade Customer File", "Certified customer files cannot be upgraded",
          "Certified customer MSISDN",
          "1. Attempt Upgrade Customer File.",
          "Upgrade is not allowed.",
          ["REQ-003"], "Not Allowed — Certified customer files", "Manual", "negative"),
        C(j, 4, "Upgrade Customer File", "Status screen shows rejection reason and missing or invalid documents",
          "Rejected file with known missing/invalid documents",
          "1. Open the status screen.",
          "System displays rejection reason, missing document(s), invalid document(s). Examples: Missing ID, Blurry ID, Missing Contract.",
          ["REQ-004", "REQ-007"], "Rejection Information / Step 2", "Manual", "positive"),
        C(j, 5, "Upgrade Customer File", "ID, Contract, Mixx indicators are green or red as stated",
          "On status screen",
          "1. Observe ID Document, Contract, Mixx Subscription.",
          "Valid: green check. Invalid/missing: red cross. Mixx is checked/unchecked, N/A for invalid.",
          ["REQ-005"], "Status Indicators", "Manual", "other"),
        C(j, 6, "Upgrade Customer File", "Valid ID or contract is view-only; invalid can be replaced",
          "One valid document and one invalid/missing document",
          "1. Attempt to replace the valid document. 2. Replace the invalid one.",
          "Valid ID/Contract is view only. Invalid/missing can be replaced.",
          ["REQ-006"], "ID Document / Contract rules", "Manual", "other"),
        C(j, 7, "Upgrade Customer File", "Mixx originally subscribed is pre-checked; checking makes contract mandatory",
          "Customer originally subscribed to Mixx",
          "1. Observe Mixx. 2. Uncheck. 3. Check again without a contract.",
          "Checkbox is already selected. User can check or uncheck. If checked, contract becomes mandatory.",
          ["REQ-008"], "Mixx Subscription", "Manual", "other"),
        C(j, 8, "Upgrade Customer File", "Supported IDs can be uploaded",
          "On document upload",
          "1. Select National ID, Passport, CEDEAO Card, Refugee Card in turn.",
          "Those ID types are supported.",
          ["REQ-009"], "Step 3", "Manual", "positive", "Medium"),
        C(j, 9, "Upgrade Customer File", "Unsupported document shows the quoted message",
          "Unsupported ID",
          "1. Upload it.",
          'Message: "Document not authorised. Please use another ID card to register client." User must upload another document.',
          ["REQ-010"], "Invalid / Unsupported Document", "Manual", "negative"),
        C(j, 10, "Upgrade Customer File", "Status refreshes immediately; Confirm enabled only when complete",
          "Missing documents remaining",
          "1. Upload a required document. 2. Attempt Confirm while items remain red. 3. Complete all items.",
          "Added documents become green check and can be replaced using Cross. Missing remain red. Confirm enabled only when all required items are completed.",
          ["REQ-011"], "Step 5 Status Refresh", "Manual", "other"),
        C(j, 11, "Upgrade Customer File", "Mixx contract shows the listed fields and requires signature",
          "Mixx selected",
          "1. Open the contract.",
          "Contract contains Date, Customer MSISDN, Customer ID Number, First Name, Last Name. Customer must provide signature. Contract is mandatory.",
          ["REQ-012"], "Step 6 Mixx Subscription Contract", "Manual", "positive"),
        C(j, 12, "Upgrade Customer File", "PIN submission and receipt contents",
          "All required items completed",
          "1. Submit. 2. Enter PIN. 3. Observe receipt. 4. Download. 5. Share.",
          "Receipt: Certification Status On Going; Activation Status Sim Activation Activated; Message SMS will be shared to client, once certification is realised; Transaction ID. Download and Share are available.",
          ["REQ-013", "REQ-014"], "Step 7 / Step 8", "Manual", "positive"),
        C(j, 13, "Upgrade Customer File", "Post-conditions: On Going, history, no stock/commission/performance impact",
          "Successful submission",
          "1. Check certification status. 2. Open history. 3. Check stock, commission, performance.",
          "Updated documents submitted to BO. Status On Going. Upgrade recorded in history. No stock, commission or performance impact.",
          ["REQ-015", "REQ-018"], "Post Conditions / History Rules", "Manual", "other", "Medium"),
        C(j, 14, "Upgrade Customer File", "AA-3 registration validation still applies",
          "Upgrade with a missing mandatory field or document",
          "1. Attempt to confirm.",
          "Mandatory documents, fields, document validation, and attachment validation from Customer Registration remain applicable.",
          ["REQ-016"], "Registration Rules", "Manual", "negative", "Medium"),
        C(j, 15, "Upgrade Customer File", "New documents are added; existing documents are retained",
          "File that already has some valid documents",
          "1. Add a new document. 2. Inspect the customer file after BO receive.",
          "Existing customer documents are retained. New documents are added to the existing file.",
          ["REQ-017"], "Sentinel Processing", "Manual", "other", "Medium"),
    ]
    return reqs, cases


def saa_920():
    j = "SAA-920"
    reqs = [
        {"id": "REQ-001", "testable": False},
    ]
    cases = [
        C(j, 1, "Reidentification within SIM Swap", "No behaviour is stated in the Jira description",
          "None — description field is empty",
          "1. Cannot design steps from evidence.",
          "Cannot be expected-resulted. getJiraIssue returned no description. Comments only attach a 10-case workbook (bytes not accessible) and note a GetSubscriberInfo API error on SAA-921. Do not copy SAA-918 re-identify buttons into this ticket.",
          ["REQ-001"], "none stated", "Manual", "other", blocked=True),
    ]
    return reqs, cases


def saa_921():
    j = "SAA-921"
    reqs = [
        {"id": "REQ-001", "testable": True},
        {"id": "REQ-002", "testable": True},
        {"id": "REQ-003", "testable": True},
        {"id": "REQ-004", "testable": True},
        {"id": "REQ-005", "testable": True},
        {"id": "REQ-006", "testable": True},
        {"id": "REQ-007", "testable": True},
        {"id": "REQ-008", "testable": True},
        {"id": "REQ-009", "testable": True},
        {"id": "REQ-010", "testable": True},
        {"id": "REQ-011", "testable": True},
        {"id": "REQ-012", "testable": True},
        {"id": "REQ-013", "testable": True},
        {"id": "REQ-014", "testable": True},
        {"id": "REQ-015", "testable": True},
        {"id": "REQ-016", "testable": True},
        {"id": "REQ-020", "testable": False},
        {"id": "REQ-021", "testable": True},
    ]
    cases = [
        C(j, 1, "Re-identification", "User selects Re-identification from Customer Services",
          LOGGED_IN, "1. Open Customer Services. 2. Select Re-identification.",
          "Re-identification starts and asks for customer MSISDN. Allowed profiles: POA, Dealer Shop, Team Leader, Staff.",
          ["REQ-001"], "Main Flow step 1", "Candidate", "positive"),
        C(j, 2, "Re-identification", "Certified customer is not authorised",
          "Certified customer MSISDN; authorised agent",
          "1. Enter the MSISDN.",
          "Re-identification is not authorised.",
          ["REQ-002"], "Customer certified", "Manual", "negative"),
        C(j, 3, "Re-identification", "Uncertified eligible customer is allowed",
          "Uncertified customer eligible on status_dossier",
          "1. Enter the MSISDN.",
          "Re-identification is allowed if eligible.",
          ["REQ-003"], "Customer uncertified", "Manual", "positive"),
        C(j, 4, "Re-identification", "Active MSISDN uses OTP with 60s timer, 5 min expiry, resend after timer, max 5, then 10 min wait",
          "Active eligible MSISDN",
          "1. Reach OTP. 2. Observe timer. 3. Wait for resend. 4. Use EnvConfig for OTP values, never workbook secrets.",
          "OTP sent to customer MSISDN. Timer default 60 seconds. Expiry 5 minutes. Resend after timer. Maximum 5 resends per session. After max attempts wait 10 minutes.",
          ["REQ-004"], "Active MSISDN – OTP Flow", "Manual", "boundary"),
        C(j, 5, "Re-identification", "Invalid OTP shows the quoted message and ends the flow",
          "On OTP step",
          "1. Enter EnvConfig testData.login.incorrectOtp. 2. Submit.",
          'Message: "Invalid OTP. The code you entered is incorrect. Please check the OTP and try again." If OTP verification fails, the flow ends.',
          ["REQ-005"], "Invalid OTP Error", "Manual", "negative"),
        C(j, 6, "Re-identification", "Inactive MSISDN uses habit questionnaire; both answers must be correct",
          "Inactive eligible MSISDN",
          "1. Enter the MSISDN. 2. Answer most frequent contact (one or two MSISDNs) and latest airtime or bundle reload correctly.",
          "Habit questionnaire is shown. Both answers must be correct to continue.",
          ["REQ-006"], "Inactive MSISDN – Customer Habit Questionnaire", "Manual", "positive"),
        C(j, 7, "Re-identification", "Failed questionnaire shows the quoted message and only Cancel",
          "Inactive MSISDN; incorrect questionnaire answers",
          "1. Submit wrong answers.",
          'Message: "Reidentification not authorised. Customer identification failed." Only Cancel is available. User cannot continue.',
          ["REQ-007"], "Failure Error", "Manual", "negative"),
        C(j, 8, "Re-identification", "Supported IDs and OCR retry",
          "Past customer verification",
          "1. Scan National ID, Foreign Passport, CEDEAO, Refugee as available. 2. Fail OCR and retry.",
          "Those ID types are supported. Front and back where required. Mandatory data from OCR or scan. If OCR fails, user can retry.",
          ["REQ-008"], "ID Scanning and OCR", "Manual", "positive", "Medium"),
        C(j, 9, "Re-identification", "Mandatory KYC fields block continue; Country and Address are editable",
          "On KYC form",
          "1. Leave ID Type, First Name, Last Name, Date of Birth, or ID Number empty. 2. Edit Country and Address.",
          "User cannot proceed until mandatory data is complete. Country and Address are editable.",
          ["REQ-009", "REQ-010"], "KYC Form Rules", "Manual", "negative"),
        C(j, 10, "Re-identification", "Unauthorised document shows the quoted message",
          "Unsupported scanned document",
          "1. Scan it.",
          'Message: "Document not authorised. Please use another ID card to register client."',
          ["REQ-011"], "Unauthorised Document", "Manual", "negative"),
        C(j, 11, "Re-identification", "SIM threshold 3 blocks with the quoted message and Home redirect",
          "Customer ID already at 3 MSISDNs",
          "1. Reach SIM threshold check.",
          'Message: "Sim threshold reached. Customer not allowed to register new numbers." User is redirected to Home.',
          ["REQ-012"], "SIM Threshold Rules", "Manual", "negative"),
        C(j, 12, "Re-identification", "Below threshold, PIN submits and receipt is shown",
          "SIM threshold passed; KYC complete",
          "1. Enter PIN. 2. Observe receipt. 3. Download. 4. Share.",
          "Receipt: Certification Status On Going; SIM Activation Status Sim Activated; Message SMS will be shared to client, once certification is realised; Transaction ID. Download and Share available.",
          ["REQ-013", "REQ-014"], "Transaction Completion / Receipt", "Manual", "positive"),
        C(j, 13, "Re-identification", "History records type, ID, date/time, certification status",
          "Successful submission",
          "1. Open agent registration history.",
          "Each re-identification is recorded with transaction type, Transaction ID, date/time, certification status.",
          ["REQ-015"], "History", "Manual", "positive", "Medium"),
        C(j, 14, "Re-identification", "Not counted in performance by default",
          "Successful re-identification; performance dashboard open",
          "1. Check whether the transaction incremented performance KPIs.",
          "Re-identification should not be counted in performance dashboard by default. Inclusion is configurable from Admin Portal by agent type (portal itself is REQ-020, not this case).",
          ["REQ-016"], "Performance", "Manual", "other", "Medium"),
        C(j, 15, "Admin Portal", "Feature flag, OTP timer, expiry, resend limits",
          "Admin Portal access",
          "1. Locate feature activation, OTP timer and expiry, OTP resend limits.",
          "Not testable from the mobile app. No portal steps.",
          ["REQ-020"], "Admin Portal Configuration", "Manual", "other", "Low"),
        C(j, 16, "Re-identification", "Comment records GetSubscriberInfo SSL failure — environment, not a product expected result",
          "If GetSubscriberInfo still fails",
          "1. Start Re-identification for an eligible MSISDN.",
          "Comment 2026-08-13 documents SSLHandshakeException on GetSubscriberInfo. That is an environment/API failure, not an acceptance criterion. If it still occurs, classify ENVIRONMENT, do not invent a UI message.",
          ["REQ-021"], "comment GetSubscriberInfo error", "Manual", "other", "Low"),
    ]
    return reqs, cases


def saa_945():
    j = "SAA-945"
    reqs = [
        {"id": "REQ-001", "testable": True},
        {"id": "REQ-002", "testable": True},
        {"id": "REQ-003", "testable": True},
        {"id": "REQ-004", "testable": True},
        {"id": "REQ-005", "testable": True},
        {"id": "REQ-006", "testable": True},
        {"id": "REQ-007", "testable": True},
        {"id": "REQ-008", "testable": True},
        {"id": "REQ-009", "testable": True},
        {"id": "REQ-010", "testable": True},
        {"id": "REQ-011", "testable": True},
        {"id": "REQ-012", "testable": True},
        {"id": "REQ-013", "testable": True},
        {"id": "REQ-014", "testable": True},
        {"id": "REQ-015", "testable": True},
        {"id": "REQ-016", "testable": True},
        {"id": "REQ-017", "testable": True},
        {"id": "REQ-018", "testable": False},
    ]
    cases = [
        C(j, 1, "New POS", "Authorised user opens New POS from the dashboard",
          "Logged in as Dealer, Supervisor, Team Leader, or Reseller",
          "1. Select New POS from the dashboard.",
          "New POS / new touchpoint flow starts. Staging PDV is not in the profile list; do not use that account for this case.",
          ["REQ-001"], "Main Flow step 1 / Applicability", "Manual", "positive"),
        C(j, 2, "New POS", "Touchpoint type is mandatory; all listed types; no profile restriction",
          "On type selection",
          "1. Attempt submit with no type. 2. Select POA, POS Airtime, POS Mixte, Dealer Shop.",
          "Selection is mandatory. Available values: POA, POS Airtime, POS Mixte, Dealer Shop. All profiles can report any type. No profile-based restrictions.",
          ["REQ-002", "REQ-003"], "Touchpoint Types", "Manual", "negative"),
        C(j, 3, "New POS", "Owner first name, last name, and MSISDN are mandatory",
          "Type selected",
          "1. Leave each owner field empty in turn and attempt submit.",
          "Owner First Name, Last Name, MSISDN are all mandatory. User cannot submit without completing owner information.",
          ["REQ-004"], "Owner Information", "Manual", "negative"),
        C(j, 4, "New POS", "Address flow requires Address/Landmark, District, City",
          "Option 1: Enter Address",
          "1. Leave each required address field empty. 2. Complete them.",
          "Address / Landmark, District, and City are required before Validate is enabled.",
          ["REQ-005", "REQ-011"], "Option 1: Enter Address / Address Flow", "Manual", "positive"),
        C(j, 5, "New POS", "District and city typing shows existing suggestions",
          "On District or City",
          "1. Start typing a known district. 2. Start typing a known city. 3. Select from the list.",
          "Existing districts and cities are suggested. User selects from available values.",
          ["REQ-006"], "District & City Search", "Manual", "positive"),
        C(j, 6, "New POS", "Map flow opens, allows any location, search suggests matches, close icon cancels",
          "Option 2: Locate Touchpoint on Map",
          "1. Open map. 2. Move and select a location. 3. Use search bar. 4. Cancel with top-right close.",
          "Map opens. User can move anywhere, select any location, search locations. Matching locations are suggested. Validate selected location or cancel via close icon.",
          ["REQ-007", "REQ-008", "REQ-009"], "Option 2: Select on Map", "Manual", "positive"),
        C(j, 7, "New POS", "No zoning, territory, or distance restriction blocks submission",
          "Location outside assigned territory, district, and zone",
          "1. Submit a touchpoint outside assigned territory, district, and zone.",
          "Request is allowed. No geographical validation should block submission.",
          ["REQ-010"], "Zoning Rules — No Restrictions", "Manual", "positive"),
        C(j, 8, "New POS", "Map Validate is enabled once a location is selected",
          "Location selected on map",
          "1. Select a location. 2. Submit.",
          "Validate button is enabled. User submits the request. Create Dealer API is used (observable by success, not by payload invention).",
          ["REQ-012", "REQ-013"], "Map Flow / Submission", "Manual", "positive"),
        C(j, 9, "New POS", "Successful submission notifies SN System, SFA, and RSS for the district",
          "Successful Create Dealer request",
          "1. Submit. 2. Check SN System ticket, SFA share, RSS notification for the selected district.",
          "New touchpoint ticket in SN System. Information shared with SFA. RSS responsible for the selected district is notified. No impact on stock, commission, or performance.",
          ["REQ-014", "REQ-015"], "Notifications / Post Conditions", "Manual", "other"),
        C(j, 10, "New POS", "Owner MSISDN from the inventory comment can be used without copying secrets into Excel",
          "Authorised account; owner MSISDN from EnvConfig inventory (comment 2026-09-20 listed test numbers)",
          "1. Enter owner MSISDN from EnvConfig, not from this workbook.",
          "Form accepts a staging owner MSISDN. Parent MSISDN asked in comment 2026-09-21 was not answered — do not invent a parent.",
          ["REQ-004"], "comment test numbers", "Manual", "other", "Medium"),
        C(j, 11, "New POS", "Figma screenshot was not readable from this session",
          "None",
          "1. Do not design extra screens from the unread PNG.",
          "Attachment image-20251008-100814.png bytes were not accessible. No extra UI is assumed.",
          ["REQ-018"], "attachment image", "Manual", "other", "Low", blocked=True),
    ]
    return reqs, cases
