from _case_factory import case as C

LOGGED_IN = "Logged in on staging with EnvConfig inventory agent (PDV) after PIN validation"


def saa_909():
    j = "SAA-909"
    reqs = [
        {"id": "REQ-001", "testable": True},
        {"id": "REQ-002", "testable": True},
        {"id": "REQ-003", "testable": True},
        {"id": "REQ-004", "testable": True},
        {"id": "REQ-005", "testable": True},
        {"id": "REQ-006", "testable": True},
        {"id": "REQ-007", "testable": True},
        {"id": "REQ-008", "testable": True},
        {"id": "REQ-009", "testable": True},
        {"id": "REQ-010", "testable": True},
        {"id": "REQ-011", "testable": True},
        {"id": "REQ-012", "testable": True},
        {"id": "REQ-013", "testable": True},
        {"id": "REQ-014", "testable": True},
        {"id": "REQ-015", "testable": True},
        {"id": "REQ-016", "testable": True},
        {"id": "REQ-017", "testable": True},
        {"id": "REQ-018", "testable": True},
        {"id": "REQ-019", "testable": True},
        {"id": "REQ-020", "testable": True},
        {"id": "REQ-021", "testable": True},
        {"id": "REQ-022", "testable": False},
    ]
    cases = [
        C(j, 1, "Dashboard", "Dashboard fits on a single screen with no scrolling",
          LOGGED_IN, "1. Open the main dashboard after login.",
          "Dashboard content is visible on one screen. No horizontal or vertical scrolling is required.",
          ["REQ-001"], "Dashboard Layout", "Candidate", "other", "Medium"),
        C(j, 2, "Dashboard", "Dashboard shows the listed sections",
          LOGGED_IN, "1. Observe Agent Information, Search, Activity History, Balance Card, QR Code, Action Buttons, Performance, Footer.",
          "Those sections are present. Banner is not asserted (REQ-022 has no trigger).",
          ["REQ-002"], "Dashboard Layout — Contain", "Candidate", "positive"),
        C(j, 3, "Dashboard", "Agent Information shows Agent Name when available",
          LOGGED_IN, "1. Read the Agent Information area.",
          "Agent Name is displayed (source: Get User Details). Do not use a secret value; match the name returned for the inventory agent.",
          ["REQ-003"], "Agent Information", "Candidate", "positive", "Medium"),
        C(j, 4, "Dashboard", "Agent Information falls back to Agent MSISDN when name is unavailable",
          "Logged in with an account whose Get User Details has no Agent Name",
          "1. Open the dashboard.",
          "Agent MSISDN is displayed in Agent Information.",
          ["REQ-003"], "If Agent Name is unavailable, display Agent MSISDN", "Manual", "other", "Medium"),
        C(j, 5, "Dashboard", "Search icon opens in-app search",
          LOGGED_IN, "1. Tap Search.",
          "Search for app sections and content is available. Result layout is not specified (Q-001).",
          ["REQ-004"], "Top Icons — Search", "Candidate", "positive", "Low"),
        C(j, 6, "Activity History", "History lists current-day app transactions only",
          "%s; at least one same-day app transaction exists" % LOGGED_IN,
          "1. Open Activity History.",
          "Only activities from today 00:00–23:59 that were performed through the app are listed.",
          ["REQ-005"], "Activity History", "Manual", "positive"),
        C(j, 7, "Activity History", "Filter by Action Type",
          "Activity History has more than one action type today",
          "1. Filter by Action Type.",
          "List shows only the selected action type. Total revenue at the bottom is recalculated.",
          ["REQ-006", "REQ-008"], "Filter by Action Type", "Manual", "other", "Medium"),
        C(j, 8, "Activity History", "Filter by Keyword / Number search",
          "Activity History has a known number or keyword",
          "1. Search by Keyword / Number.",
          "Matching transactions remain. Revenue is recalculated after filtering.",
          ["REQ-006", "REQ-008"], "Keyword / Number Search", "Manual", "other", "Medium"),
        C(j, 9, "Activity History", "Transactions are in chronological order",
          "At least two same-day transactions",
          "1. Open Activity History with no filter.",
          "Transactions are sorted chronologically. Record whether newest-first or oldest-first (Q-002).",
          ["REQ-007"], "Transactions sorted in chronological order", "Manual", "other", "Medium"),
        C(j, 10, "Activity History", "Supported history types can appear in the list",
          "Same-day transactions exist for Registration, Re-identification, SIM Swap, Upgrade Account, Upgrade KYC, Airtime, Bundle",
          "1. Open Activity History. 2. Filter or scan by type.",
          "Each of the seven stored types can appear when a matching same-day transaction exists.",
          ["REQ-009"], "Supported History Types", "Manual", "other", "Medium"),
        C(j, 11, "Balance", "Airtime balance is present after PIN validation",
          LOGGED_IN, "1. Observe the Balance Card.",
          "Airtime (Yas) balance area is present. Refresh latency is not asserted (Q-003).",
          ["REQ-010"], "Airtime Balance", "Candidate", "positive"),
        C(j, 12, "Balance", "Balance is hidden by default and revealed with the Eye icon",
          LOGGED_IN, "1. Observe the amount. 2. Tap the Eye icon.",
          "Amount is hidden by default. After Eye, the amount is revealed.",
          ["REQ-011"], "Hidden by default, Eye icon", "Candidate", "other"),
        C(j, 13, "QR Code", "QR code is shown as the agent identifier",
          LOGGED_IN, "1. Observe the QR on the dashboard.",
          "QR code is visible for the logged-in agent.",
          ["REQ-012"], "QR Code — Available for all agents", "Candidate", "positive", "Medium"),
        C(j, 14, "QR Code", "Tapping QR expands it with Agent MSISDN above",
          LOGGED_IN, "1. Tap the QR code.",
          "QR expands to full screen. Agent MSISDN is displayed above it.",
          ["REQ-013"], "On click", "Candidate", "other", "Medium"),
        C(j, 15, "Action Buttons", "Buttons with authorized=true are displayed",
          "Agent Profile Mapping has at least one authorized=true action",
          "1. Observe action buttons.",
          "Buttons whose mapping is authorized=true are displayed.",
          ["REQ-014"], "Authorized = true → Button displayed", "Manual", "positive"),
        C(j, 16, "Action Buttons", "Buttons with authorized=false are hidden",
          "Agent Profile Mapping has at least one authorized=false action",
          "1. Observe action buttons.",
          "Buttons whose mapping is authorized=false are not displayed.",
          ["REQ-014"], "Authorized = false → Button hidden", "Manual", "negative"),
        C(j, 17, "Dashboard", "Freelancer / Staff dashboard shows the listed sections and three common actions",
          "Logged in as Freelancer 1, Freelancer 2, or Staff",
          "1. Open the dashboard.",
          "Search, Activity History, Agent Information, Airtime Balance, Performance, Client Registration, Airtime & Bundle, Customer Services are present. Banner not asserted.",
          ["REQ-015"], "Dashboard by User Type — Freelancer / Staff", "Manual", "positive"),
        C(j, 18, "Dashboard", "Team Leader dashboard additionally shows Agent Out of Stock and Reload",
          "Logged in as Team Leader",
          "1. Open the dashboard.",
          "Team Leader sees the Freelancer/Staff set plus Agent Out of Stock and Reload.",
          ["REQ-016"], "Team Leader", "Manual", "positive"),
        C(j, 19, "Performance", "Performance shows at most two KPI cards with current and previous-day comparison",
          LOGGED_IN, "1. Observe the Performance section.",
          "At most 2 KPI cards. Current value and previous-day comparison are shown. Gross Add at D+1 is not asserted unless D+1 data is present.",
          ["REQ-017"], "Performance Section — General Rules", "Candidate", "boundary", "Medium"),
        C(j, 20, "Performance", "Each KPI uses the stated comparison baseline",
          "KPI values are available from agentPerformance API",
          "1. Read each visible KPI comparison label.",
          "Registration, Certification, Active Agents, Airtime Sales, Reload, POS Out of Stock compare vs Yesterday. Gross Add compares vs Target.",
          ["REQ-018"], "KPI Comparison Logic", "Manual", "other", "Medium"),
        C(j, 21, "Performance", "Indicator is Up/Green, Down/Red, or Horizontal/Orange",
          "Controllable KPI data for current > / < / = comparison",
          "1. Observe the indicator on a KPI where current is greater, lower, then equal.",
          "Greater: Up, Green. Lower: Down, Red. Equal: Horizontal, Orange. Hex values are not specified.",
          ["REQ-019"], "Performance Indicators", "Manual", "other", "Medium"),
        C(j, 22, "Performance", "Team Leader performance shows cumulative team KPIs",
          "Logged in as Team Leader",
          "1. Open Performance.",
          "Values are cumulative team performance for Registration, Certification, Gross Add, Active Agents with today, yesterday, and trend.",
          ["REQ-020"], "Team Leader Performance", "Manual", "positive", "Medium"),
        C(j, 23, "Footer", "Footer is visible with Home, Notifications, My Account",
          LOGGED_IN, "1. Observe the footer. 2. Tap Home, Notifications, My Account in turn.",
          "Footer is visible. Home opens Main Dashboard. Notifications opens Notification Centre. My Account opens Profile / Self-Care.",
          ["REQ-021"], "Footer", "Candidate", "positive"),
        C(j, 24, "Banner", "Banner display depends on downstream API — expected content not stated",
          LOGGED_IN, "1. Observe whether a banner is present.",
          "Cannot be expected-resulted. Banner content, count and trigger are not in the ticket.",
          ["REQ-022"], "Banner", "Manual", "other", "Low", blocked=True),
    ]
    return reqs, cases


def saa_910():
    j = "SAA-910"
    reqs = [
        {"id": "REQ-001", "testable": True},
        {"id": "REQ-002", "testable": True},
        {"id": "REQ-003", "testable": True},
        {"id": "REQ-004", "testable": True},
        {"id": "REQ-005", "testable": True},
        {"id": "REQ-006", "testable": True},
        {"id": "REQ-007", "testable": True},
        {"id": "REQ-008", "testable": True},
        {"id": "REQ-009", "testable": True},
        {"id": "REQ-010", "testable": True},
        {"id": "REQ-011", "testable": True},
        {"id": "REQ-012", "testable": True},
        {"id": "REQ-013", "testable": False},
        {"id": "REQ-014", "testable": True},
        {"id": "REQ-015", "testable": True},
        {"id": "REQ-016", "testable": True},
        {"id": "REQ-017", "testable": False},
        {"id": "REQ-018", "testable": True},
        {"id": "REQ-019", "testable": True},
        {"id": "REQ-020", "testable": True},
        {"id": "REQ-021", "testable": True},
        {"id": "REQ-022", "testable": True},
        {"id": "REQ-023", "testable": True},
        {"id": "REQ-024", "testable": True},
    ]
    cases = [
        C(j, 1, "Customer Registration", "Agent opens Client Registration and selects an available MSISDN",
          LOGGED_IN + "; available MSISDN stock on staging",
          "1. Open Client Registration. 2. Select one available MSISDN.",
          "An available MSISDN is selected and the flow continues to customer details.",
          ["REQ-001"], "Step 1: Select MSISDN", "Candidate", "positive"),
        C(j, 2, "Customer Registration", "KYC form captures the named customer fields",
          "On customer details after MSISDN select",
          "1. Observe First Name, Last Name, Date of Birth, Address, Nationality, ID Type, ID Number, Alternate Number.",
          "Those fields are present. Other mandatory KYC fields are not named (Q-001) and are not invented.",
          ["REQ-002"], "Step 2: Enter Customer Details", "Manual", "positive"),
        C(j, 3, "Customer Registration", "Registration allowed when customer has fewer than 3 active SIMs",
          "Customer ID with 2 active SIMs (boundary below threshold)",
          "1. Complete details for that customer and proceed past SIM check.",
          "Registration is allowed.",
          ["REQ-003"], "Step 3 — Allowed", "Manual", "boundary"),
        C(j, 4, "Customer Registration", "Three or more SIMs show a threshold message and SIM Swap shortcut",
          "Customer ID with 3 active SIMs",
          "1. Proceed to SIM threshold check.",
          "A SIM threshold exceeded message is shown. Registration stops. A shortcut to SIM Swap is offered. Exact wording is not quoted (Q-002).",
          ["REQ-004"], "Step 3 — Blocked", "Manual", "negative"),
        C(j, 5, "Customer Registration", "Incomplete application cannot be submitted",
          "On a registration step with a mandatory field empty",
          "1. Leave a mandatory field empty. 2. Attempt to continue or submit. 3. Attempt to skip a step.",
          "Mandatory fields cannot be empty. Required documents and images are required. No step can be skipped. Incomplete application cannot be submitted.",
          ["REQ-005"], "Mandatory Completion Rules", "Manual", "negative"),
        C(j, 6, "Attachments", "Senegalese ID Card requires front, back, and customer photo",
          "Personal registration; Senegalese ID Card selected; MFS not selected",
          "1. Attempt to continue without each of ID Front, ID Back, Customer Photo in turn.",
          "Each of ID Front, ID Back, and Customer Photo is required. Contract is not required.",
          ["REQ-006", "REQ-012"], "Attachment Rules — Senegalese ID Card", "Manual", "positive"),
        C(j, 7, "Attachments", "Passport requires passport image and customer photo",
          "Personal registration; Passport selected; MFS not selected",
          "1. Attempt to continue without Passport Image, then without Customer Photo.",
          "Passport Image and Customer Photo are required.",
          ["REQ-007"], "Passport", "Manual", "positive"),
        C(j, 8, "Attachments", "CEDEAO Card requires front, back, and customer photo",
          "Personal registration; CEDEAO Card selected",
          "1. Attempt to continue without Front, Back, or Customer Photo.",
          "Front, Back, and Customer Photo are required.",
          ["REQ-008"], "CEDEAO Card", "Manual", "positive"),
        C(j, 9, "Attachments", "Refugee Card requires front, back, and customer photo",
          "Personal registration; Refugee Card selected",
          "1. Attempt to continue without Front, Back, or Customer Photo.",
          "Front, Back, and Customer Photo are required.",
          ["REQ-009"], "Refugee Card", "Manual", "positive"),
        C(j, 10, "Attachments", "Procuration registration requires the procuration document",
          "Procuration registration type selected",
          "1. Attempt to continue without the procuration document. 2. Upload it and submit.",
          "Procuration document is required. Request sends IsProcuration = 1 (backend evidence, not a UI assertion).",
          ["REQ-010"], "Procuration Registration", "Manual", "positive"),
        C(j, 11, "MFS Wallet", "MFS selected makes signature contract mandatory",
          "MFS wallet selected (mfsWallet = 1)",
          "1. Attempt to continue without the contract image.",
          "Customer signature contract is mandatory and the contract image must be uploaded.",
          ["REQ-011"], "MFS Wallet Selected", "Manual", "positive"),
        C(j, 12, "MFS Wallet", "MFS not selected does not require a contract",
          "MFS wallet not selected",
          "1. Complete registration without uploading a contract.",
          "Contract image is not required and should not be uploaded.",
          ["REQ-012"], "MFS Wallet Not Selected", "Manual", "negative", "Medium"),
        C(j, 13, "Auto Certification", "Auto certification payload is not stated",
          "Customer already has at least one SIM and KYC is unchanged",
          "1. Submit registration.",
          "Cannot be expected-resulted. The ticket's Send line is blank.",
          ["REQ-013"], "Auto Certification Rules", "Manual", "other", "Medium", blocked=True),
        C(j, 14, "Attachments", "Uploaded file names follow the stated pattern",
          "Successful document upload; access to stored files",
          "1. Upload required documents. 2. Inspect stored file names.",
          "Names match 1_<SubscriberMSISDN>_<AgentMSISDN>_<Timestamp>_<DocumentType>.jpg with the document types listed in the ticket.",
          ["REQ-014"], "Attachment Naming Validation", "Manual", "other", "Medium"),
        C(j, 15, "Receipt", "Successful registration receipt shows Transaction ID and Certification Status",
          "Registration submitted successfully",
          "1. Observe the receipt.",
          "Receipt displays Transaction ID and Certification Status. Allowed status values are not listed.",
          ["REQ-015"], "Receipt Screen", "Manual", "positive"),
        C(j, 16, "Receipt", "Receipt can be downloaded, shared, and sent via device apps",
          "On the receipt screen",
          "1. Download. 2. Share. 3. Send via email or another device app.",
          "Download, share, and send via email/apps supported by the device are available.",
          ["REQ-016"], "Receipt Actions", "Manual", "positive", "Medium"),
        C(j, 17, "Admin Portal", "SIM threshold and country rules are configurable from Admin Portal",
          "Admin Portal access",
          "1. Locate SIM threshold and country-specific registration rules.",
          "Not testable from the mobile app. No portal steps are in the ticket.",
          ["REQ-017"], "Admin Portal Configuration", "Manual", "other", "Low"),
        C(j, 18, "MVP CR", "Senegalese passport is recorded as Senegalese Id Card with ID = MRZ Opt1",
          "Senegalese passport available for OCR",
          "1. Scan a Senegalese passport.",
          "Document is marked as Senegalese Id Card. Numéro de la pièce d'identité = MRZ Opt1.",
          ["REQ-018"], "MVP CR changes — SENEGAL passport", "Manual", "positive"),
        C(j, 19, "MVP CR", "Non-Senegalese passport is recorded as passport with ID = passportNumber",
          "Foreign passport available",
          "1. Scan a non-Senegalese passport.",
          "Document is marked as passport. ID number = passportNumber.",
          ["REQ-019"], "MVP CR changes — Else branch", "Manual", "positive"),
        C(j, 20, "Address", "Senegalese ID card makes address mandatory and read-only",
          "DocumentType id, isoAlpha2CountryCode SN",
          "1. Observe the address field.",
          "Address is mandatory and read-only. Literal value Address vs card address is Q-006; assert mandatory + read-only only.",
          ["REQ-020"], "id / SN address", "Manual", "other", "Medium"),
        C(j, 21, "Address", "CEDEAO card makes address mandatory and editable",
          "isoAlpha2CountryCode in BJ, GN, GW, GM, SL, NG, ML",
          "1. Observe and edit the address field.",
          "Address is mandatory and the agent can fill it.",
          ["REQ-021"], "CEDEAO address", "Manual", "other", "Medium"),
        C(j, 22, "Address", "Passport makes address mandatory and editable",
          "DocumentType.id = passport",
          "1. Observe and edit the address field.",
          "Address is mandatory and editable.",
          ["REQ-022"], "passport address", "Manual", "other", "Medium"),
        C(j, 23, "MRZ", "ID card MRZ mismatch on name or date of birth stops the flow",
          "Senegalese ID or CEDEAO where first name, last name, or DOB disagrees with MRZ",
          "1. Scan the ID. 2. Present a mismatch on SecondaryId, PrimaryId, or DateOfBirth.",
          "Flow stops. Message text is not quoted (Q-005).",
          ["REQ-023"], "MRZ comparison, ID branches", "Manual", "negative"),
        C(j, 24, "MRZ", "Passport MRZ mismatch including DocumentNumber stops the flow",
          "Senegal or foreign passport with a DocumentNumber mismatch",
          "1. Scan the passport with DocumentNumber disagreeing with MRZ DocumentNumber.",
          "Flow stops. Message text is not quoted.",
          ["REQ-024"], "MRZ comparison, passport branches", "Manual", "negative"),
    ]
    return reqs, cases


def saa_911():
    j = "SAA-911"
    reqs = [
        {"id": "REQ-001", "testable": True},
        {"id": "REQ-002", "testable": False},
        {"id": "REQ-003", "testable": True},
        {"id": "REQ-004", "testable": True},
        {"id": "REQ-005", "testable": True},
    ]
    cases = [
        C(j, 1, "Inactivity Logout", "Agent is logged out after the configured inactivity period with no touch",
          "%s; inactivity minutes named in EnvConfig testData.session.inactivityTimeoutMinutes" % LOGGED_IN,
          "1. Leave the app open with no action and no screen touch for the configured minutes.",
          "Agent is automatically logged out after that period.",
          ["REQ-001"], "automatically logged out after a given period of time", "Manual", "positive"),
        C(j, 2, "Inactivity Logout", "A screen touch before the period resets inactivity",
          "Configured timeout known",
          "1. Wait until just before the timeout. 2. Touch the screen. 3. Wait the same period again without timeout.",
          "The agent remains logged in after the first interval because of the touch. Logout still occurs after a full untouched period.",
          ["REQ-003"], "no action on the app, nor touch the screen", "Manual", "other"),
        C(j, 3, "Inactivity Logout", "Returning to the app before the period ends does not require a new login",
          LOGGED_IN,
          "1. Send the app to background for a few seconds (well below any configured timeout). 2. Re-open the agent app.",
          "The agent re-enters without logging in.",
          ["REQ-005"], "able to reenter the agent app without login in, if the time is not yet up", "Candidate", "other"),
        C(j, 4, "Inactivity Logout", "Timeout continues while the app is in the background",
          "Configured timeout known",
          "1. Background the app. 2. Wait until the configured period has elapsed. 3. Re-open the app.",
          "The agent is logged out. Timeout applied even when the user left the app.",
          ["REQ-004", "REQ-001"], "should apply, even when user leaves the app", "Manual", "other"),
        C(j, 5, "Inactivity Logout", "Just-before vs at-timeout boundary",
          "Configured timeout known",
          "1. Stay inactive until just before the configured minute. 2. Repeat until the configured minute has elapsed.",
          "Still logged in just before. Logged out at or after the period. Record whether logout is exact or on next interaction (Q-003).",
          ["REQ-001"], "given period of time", "Manual", "boundary"),
        C(j, 6, "Inactivity Logout", "Screen shown after automatic logout is not stated",
          "After an automatic logout",
          "1. Observe the destination screen and any message.",
          "Cannot be expected-resulted. Destination (MSISDN, PIN, or splash) and message are not in the ticket.",
          ["REQ-001"], "automatically logged out", "Manual", "other", blocked=True),
        C(j, 7, "Admin Portal", "Timeout is configurable in minutes per profile",
          "Admin Portal access",
          "1. Locate inactivity timeout in minutes per profile.",
          "Not testable from the mobile app. No portal steps are in the ticket.",
          ["REQ-002"], "manageable through the admin portal", "Manual", "other", "Medium"),
    ]
    return reqs, cases


def saa_912():
    j = "SAA-912"
    reqs = [
        {"id": "REQ-001", "testable": True},
        {"id": "REQ-002", "testable": True},
        {"id": "REQ-003", "testable": True},
        {"id": "REQ-004", "testable": True},
        {"id": "REQ-005", "testable": True},
        {"id": "REQ-006", "testable": True},
        {"id": "REQ-007", "testable": True},
        {"id": "REQ-008", "testable": True},
        {"id": "REQ-009", "testable": True},
        {"id": "REQ-010", "testable": True},
        {"id": "REQ-011", "testable": True},
        {"id": "REQ-012", "testable": False},
    ]
    cases = [
        C(j, 1, "Customer Services", "Customer Services asks for the customer MSISDN",
          LOGGED_IN, "1. Open Customer Services from the dashboard.",
          "Customer Services opens and asks for the customer MSISDN.",
          ["REQ-001"], "Basic Flow 1–2", "Candidate", "positive"),
        C(j, 2, "Customer Services", "Valid MSISDN returns certification status and eligible actions",
          "Accredited agent; valid customer MSISDN on staging",
          "1. Enter the customer MSISDN. 2. Submit.",
          "Certification status is shown. Eligible actions are displayed.",
          ["REQ-002"], "Basic Flow 3–5", "Manual", "positive"),
        C(j, 3, "Customer Services", "Invalid or inactive MSISDN shows the quoted message",
          LOGGED_IN + "; on Customer Services MSISDN entry",
          "1. Enter EnvConfig testData.login.invalidMsisdnFormat. 2. Submit.",
          'Message: "It seems the MSISDN entered is either incorrect or inactive."',
          ["REQ-003"], "MSISDN Validation", "Candidate", "negative"),
        C(j, 4, "Customer Services", "POS / POA / Cash Point / Agent Account MSISDN does not offer Telco actions",
          "MSISDN of an active POS, POA, Cash Point, or Agent Account",
          "1. Enter that MSISDN.",
          "SIM Swap, Re-identification, and Upgrade Customer File are not allowed. Assert those three actions are absent (Q-001).",
          ["REQ-004"], "Agent Account Restrictions", "Manual", "negative"),
        C(j, 5, "Customer Services", "Non-accredited agent can view certification status",
          "Non-accredited agent account; valid customer MSISDN",
          "1. Enter the MSISDN.",
          "Certification status is visible.",
          ["REQ-005"], "Non-Accredited Users — Allowed", "Manual", "positive"),
        C(j, 6, "Customer Services", "Non-accredited agent sees no action buttons",
          "Non-accredited agent; valid customer MSISDN",
          "1. Enter the MSISDN.",
          "No action buttons are displayed. SIM Swap, Re-identification, Upgrade Customer File, Subscribe to Mixx by Yas are absent.",
          ["REQ-006", "REQ-011"], "UI Behaviour — No action buttons displayed", "Manual", "negative"),
        C(j, 7, "Eligibility", "Certified Telco + MFS shows SIM Swap only",
          "Accredited agent; Certified Telco + MFS customer",
          "1. Enter the MSISDN.",
          "SIM Swap is shown. Re-identification, Upgrade Customer File, Mixx by Yas are not.",
          ["REQ-007", "REQ-011"], "matrix row 1", "Manual", "other"),
        C(j, 8, "Eligibility", "Certified Telco Only shows SIM Swap and Mixx by Yas",
          "Accredited agent; Certified Telco Only customer",
          "1. Enter the MSISDN.",
          "SIM Swap and Mixx by Yas are shown. Re-identification and Upgrade Customer File are not.",
          ["REQ-008", "REQ-011"], "matrix row 2", "Manual", "other"),
        C(j, 9, "Eligibility", "Non-Certified shows SIM Swap, Re-identification, Upgrade Customer File",
          "Accredited agent; Non-Certified customer",
          "1. Enter the MSISDN.",
          "SIM Swap, Re-identification, Upgrade Customer File are shown. Mixx by Yas is not.",
          ["REQ-009", "REQ-011"], "matrix row 3", "Manual", "other"),
        C(j, 10, "Eligibility", "Status_Dossier 0-dossier allows SIM Swap/Re-identification and Upgrade Customer File",
          "Customer with Status_Dossier 0-dossier",
          "1. Enter the MSISDN.",
          "SIM Swap / Re-identification allowed. Upgrade KYC not allowed. Upgrade Customer File allowed.",
          ["REQ-010"], "Senegal Eligibility Rules — 0-dossier", "Manual", "other"),
        C(j, 11, "Eligibility", "Status_Dossier A régulariser",
          "Customer A régulariser", "1. Enter the MSISDN.",
          "SIM Swap / Re-identification allowed. Upgrade KYC not. Upgrade Customer File allowed.",
          ["REQ-010"], "A régulariser", "Manual", "other"),
        C(j, 12, "Eligibility", "Status_Dossier Ré-initié",
          "Customer Ré-initié", "1. Enter the MSISDN.",
          "SIM Swap / Re-identification, Upgrade KYC, and Upgrade Customer File all allowed.",
          ["REQ-010"], "Ré-initié", "Manual", "other"),
        C(j, 13, "Eligibility", "Status_Dossier Initié",
          "Customer Initié", "1. Enter the MSISDN.",
          "SIM Swap / Re-identification allowed. Upgrade KYC not. Upgrade Customer File allowed.",
          ["REQ-010"], "Initié", "Manual", "other"),
        C(j, 14, "Eligibility", "Status_Dossier Identifié",
          "Customer Identifié", "1. Enter the MSISDN.",
          "SIM Swap / Re-identification not allowed. Upgrade KYC and Upgrade Customer File allowed.",
          ["REQ-010"], "Identifié", "Manual", "other"),
        C(j, 15, "Eligibility", "Status_Dossier Certifié",
          "Customer Certifié", "1. Enter the MSISDN.",
          "SIM Swap / Re-identification not. Upgrade KYC allowed. Upgrade Customer File not.",
          ["REQ-010"], "Certifié", "Manual", "other"),
        C(j, 16, "Eligibility", "Status_Dossier Migré",
          "Customer Migré", "1. Enter the MSISDN.",
          "SIM Swap / Re-identification allowed. Upgrade KYC not. Upgrade Customer File allowed.",
          ["REQ-010"], "Migré", "Manual", "other"),
        C(j, 17, "Eligibility", "Status_Dossier A certifier",
          "Customer A certifier", "1. Enter the MSISDN.",
          "SIM Swap / Re-identification not. Upgrade KYC allowed. Upgrade Customer File not.",
          ["REQ-010"], "A certifier", "Manual", "other"),
        C(j, 18, "Eligibility", "Status_Dossier Identifié avec complement MFS",
          "Customer Identifié avec complement MFS", "1. Enter the MSISDN.",
          "SIM Swap / Re-identification not. Upgrade KYC not. Upgrade Customer File allowed.",
          ["REQ-010"], "Identifié avec complement MFS", "Manual", "other"),
        C(j, 19, "Eligibility", "Status_Dossier Ré-initié après migration",
          "Customer Ré-initié après migration", "1. Enter the MSISDN.",
          "SIM Swap / Re-identification allowed. Upgrade KYC not. Upgrade Customer File allowed.",
          ["REQ-010"], "Ré-initié après migration", "Manual", "other"),
        C(j, 20, "Eligibility", "Status_Dossier Ré-identifié",
          "Customer Ré-identifié", "1. Enter the MSISDN.",
          "SIM Swap / Re-identification allowed. Upgrade KYC not. Upgrade Customer File allowed.",
          ["REQ-010"], "Ré-identifié", "Manual", "other"),
        C(j, 21, "Eligibility", "How the general matrix and Senegal table combine is not stated",
          "A customer where the 3-row matrix and Status_Dossier table disagree",
          "1. Enter that MSISDN.",
          "Cannot be expected-resulted. Combination rule and Upgrade KYC vs Action Buttons list are Q-002.",
          ["REQ-010"], "contradiction between tables", "Manual", "other", blocked=True),
        C(j, 22, "Upgrade Customer File", "tsARTService call for missing documents is optional and not specified",
          "Upgrade Customer File with missing documents",
          "1. Open Upgrade Customer File.",
          "Not independently testable. Ticket says the system may call tsARTService.",
          ["REQ-012"], "For Upgrade Customer File", "Manual", "other", "Low"),
    ]
    return reqs, cases
