from _case_factory import case as C

LOGGED_IN = "Logged in on staging with EnvConfig inventory agent (PDV) after PIN validation"


def saa_913():
    j = "SAA-913"
    reqs = [
        {"id": "REQ-001", "testable": True},
        {"id": "REQ-002", "testable": True},
        {"id": "REQ-003", "testable": True},
        {"id": "REQ-004", "testable": True},
        {"id": "REQ-005", "testable": True},
        {"id": "REQ-006", "testable": True},
        {"id": "REQ-007", "testable": True},
        {"id": "REQ-008", "testable": True},
        {"id": "REQ-009", "testable": True},
        {"id": "REQ-010", "testable": True},
        {"id": "REQ-011", "testable": True},
        {"id": "REQ-012", "testable": True},
        {"id": "REQ-013", "testable": True},
        {"id": "REQ-014", "testable": True},
        {"id": "REQ-015", "testable": True},
        {"id": "REQ-016", "testable": True},
        {"id": "REQ-017", "testable": True},
        {"id": "REQ-018", "testable": True},
        {"id": "REQ-019", "testable": True},
        {"id": "REQ-020", "testable": True},
        {"id": "REQ-021", "testable": True},
        {"id": "REQ-022", "testable": True},
        {"id": "REQ-023", "testable": True},
        {"id": "REQ-024", "testable": True},
        {"id": "REQ-025", "testable": True},
    ]
    cases = [
        C(j, 1, "Performance Dashboard", "User can open Performance from the main dashboard",
          LOGGED_IN, "1. Open Performance Dashboard from Main Dashboard.",
          "Performance Dashboard is reachable from Main Dashboard, subject to profile/accreditation.",
          ["REQ-001", "REQ-002"], "Access — Main Dashboard", "Candidate", "positive"),
        C(j, 2, "Performance Dashboard", "User can open Performance from My Profile",
          LOGGED_IN, "1. Open My Account / My Profile. 2. Open Performance Dashboard.",
          "Performance Dashboard is reachable from My Profile.",
          ["REQ-001"], "Access — My Profile", "Candidate", "positive", "Medium"),
        C(j, 3, "Performance Dashboard", "Team Leader can select the four dashboard types",
          "Logged in as Team Leader",
          "1. Open Performance. 2. Observe the selection screen.",
          "Team Leader can select Registration & Customer Services, Airtime and Bundle Sales, Reload, Team Performance.",
          ["REQ-003"], "Dashboard Entry Rules — Team Leader", "Manual", "positive"),
        C(j, 4, "Performance Dashboard", "Non-TL non-Reseller can select Registration and Airtime only",
          "Logged in as a profile that is not Team Leader and not Reseller",
          "1. Open Performance.",
          "Selection offers Registration & Customer Services and Airtime and Bundle Sales only.",
          ["REQ-004"], "Other Profiles except Team Leader and Reseller", "Manual", "positive"),
        C(j, 5, "Performance Dashboard", "Reseller is redirected to Reload Dashboard with no selection screen",
          "Logged in as Reseller",
          "1. Open Performance.",
          "No selection screen. User is redirected directly to Reload Dashboard.",
          ["REQ-005"], "Reseller", "Manual", "positive"),
        C(j, 6, "Performance Dashboard", "Dashboards are available only for accredited features",
          "User accredited for a subset of registration / airtime / reload / team",
          "1. Open Performance.",
          "Customer Registration & Certification, Airtime, Reload, Team Performance appear only for the accredited features listed in the ticket table.",
          ["REQ-006"], "Available MVP Dashboards", "Manual", "other"),
        C(j, 7, "Filters", "Period filters Today / This Week / This Month with previous-period logic",
          "On a Performance dashboard with KPIs",
          "1. Filter Today. 2. This Week. 3. This Month.",
          "Today compares with Yesterday. This Week with Previous Week. This Month with Previous Month.",
          ["REQ-007"], "Dashboard Period Filters", "Candidate", "other", "Medium"),
        C(j, 8, "Filters", "History can be filtered by transaction category and certification status",
          "History records exist",
          "1. Filter by transaction category. 2. Filter by certification status where applicable.",
          "History filters by transaction category and, where applicable, certification status.",
          ["REQ-008"], "History Filters", "Manual", "other", "Medium"),
        C(j, 9, "Registration Dashboard", "Registration KPIs are displayed",
          "Accredited for registration; KPI data present",
          "1. Open Registration & Customer Services dashboard.",
          "Shows total registrations, registration target, previous period, certified, ongoing, rejected, Gross Add at D+1, GA Target.",
          ["REQ-009"], "Registration KPIs Displayed", "Manual", "positive"),
        C(j, 10, "Registration Dashboard", "History includes Registration, SIM Swap, Re-identification, Upgrade Customer File",
          "Same-period transactions of those types",
          "1. Open history.",
          "Those four types can appear. Each record shows Transaction ID, date and time, certification status Certified / Ongoing / Rejected.",
          ["REQ-010"], "History Includes / History Details", "Manual", "positive"),
        C(j, 11, "Registration Dashboard", "Rejected history shows reason and Upgrade Customer File",
          "A rejected customer file in history",
          "1. Open the rejected record.",
          "Rejection reason is shown. Upgrade Customer File button redirects to the upgrade flow.",
          ["REQ-011"], "If rejected", "Manual", "positive"),
        C(j, 12, "Transaction Details", "Opening a registration-family transaction shows the stated fields",
          "A Registration / SIM Swap / Re-identification / Upgrade File record",
          "1. Open the transaction.",
          "Shows transaction name, Transaction ID, date and time, certification status, rejection reason if applicable, Need Help.",
          ["REQ-012"], "Transaction Details – Registration / SIM Swap / Re-identification / Upgrade File", "Manual", "positive"),
        C(j, 13, "Transaction Details", "Rejected file upgrade pre-fills the customer number",
          "Rejected customer file",
          "1. Tap Upgrade Customer File.",
          "Upgrade flow opens with customer number pre-filled.",
          ["REQ-013"], "For rejected customer files", "Manual", "positive"),
        C(j, 14, "Airtime Dashboard", "Airtime KPIs and history details",
          "Accredited for airtime; sales exist",
          "1. Open Airtime dashboard. 2. Open a history row.",
          "KPIs: total volume sold, target, previous period (airtime includes bundle). History: airtime and bundle sales with date/time, customer MSISDN, top-up/bundle, cost, commission if applicable.",
          ["REQ-014", "REQ-015"], "Airtime Dashboard", "Manual", "positive"),
        C(j, 15, "Airtime Dashboard", "Airtime / bundle transaction details",
          "An airtime or bundle transaction",
          "1. Open the transaction.",
          "Shows Airtime Top-up or Bundle Subscription, Transaction ID, date/time, customer MSISDN, amount credited, bundle name if applicable, commission if applicable, Need Help.",
          ["REQ-016"], "Transaction Details – Airtime / Bundle", "Manual", "positive"),
        C(j, 16, "Reload Dashboard", "Reload KPIs and history types",
          "Accredited for reload",
          "1. Open Reload dashboard.",
          "KPIs for airtime and mobile money volume (total, target, previous). History includes Airtime, Mobile Money, Scratch Card, SIM Card reloads with date/time, Agent MSISDN, product and amount, transaction cost.",
          ["REQ-017", "REQ-018"], "Reload Dashboard", "Manual", "positive"),
        C(j, 17, "Reload Dashboard", "Reload received vs sent details",
          "A reload received and a reload sent record",
          "1. Open Reload Received. 2. Open Reload Sent.",
          "Received shows reseller name and MSISDN who sent. Sent shows agent name and MSISDN who received. Both show name Reload Received/Sent, Transaction ID, date/time, product and amount, total cost, Need Help.",
          ["REQ-019"], "Transaction Details – Reload", "Manual", "positive"),
        C(j, 18, "Claims", "Need Help on a reload offers hotline and the quoted question",
          "On a reload transaction detail",
          "1. Tap Need Help.",
          'Hotline is available and dials the configured number. Question: "Do you have an issue with this transaction?" Options: Issue with SIM card, scratch card or device received; Other, write directly to help centre. Submitted claim is shared with Back Office.',
          ["REQ-020"], "Claims from Reload Transaction", "Manual", "positive"),
        C(j, 19, "Team Performance", "Team Leader / Supervisor KPIs and active-agent rule",
          "Logged in as Team Leader or Supervisor",
          "1. Open Team Performance.",
          "KPIs: active/inactive agents, reload or registration performance by profile, active agents target, previous period, plus dashboard-type KPIs. Agent is active if they completed at least one App or USSD transaction in the selected period.",
          ["REQ-021"], "Team Performance Dashboard", "Manual", "positive"),
        C(j, 20, "Team Performance", "Supervisor / Reseller team dashboard history restrictions",
          "Logged in as Supervisor",
          "1. Open team dashboard. 2. Attempt to open a detailed transaction.",
          "History includes working days and the four reload types. Supervisor can view agent activity history and cannot view detailed transaction history.",
          ["REQ-022"], "Supervisor / Reseller Team Dashboard", "Manual", "negative"),
        C(j, 21, "Team Performance", "Team Leader registration dashboard KPIs",
          "Logged in as Team Leader on registration dashboard",
          "1. Observe KPIs.",
          "Total active agents, target, previous; total registrations, target, previous; certified, ongoing, rejected.",
          ["REQ-023"], "Team Leader Registration Dashboard", "Manual", "positive"),
        C(j, 22, "Selected Agent", "Team Leader can view a selected agent's dashboard but not details or upgrade",
          "Team Leader with at least one agent in the team",
          "1. Select an agent. 2. Attempt to open a transaction. 3. Attempt Upgrade Customer File.",
          "Shows agent name, MSISDN, Active/Inactive. KPIs match that agent's personal dashboard. History shows type, ID, date/time, certification, rejection reason. Team Leader cannot open transaction details and cannot upgrade customer file from this view.",
          ["REQ-024", "REQ-025"], "View Selected Agent Dashboard", "Manual", "negative"),
        C(j, 23, "Performance Dashboard", "Telco Sales target section is removed",
          "On Telco Sales / Airtime area",
          "1. Look for a Target section in Telco Sales.",
          "Target section in Telco Sales is not present.",
          ["REQ-001"], "Target section in Telco Sales will be removed", "Manual", "other", "Low"),
    ]
    return reqs, cases


def saa_914():
    j = "SAA-914"
    reqs = [
        {"id": "REQ-001", "testable": True},
        {"id": "REQ-002", "testable": True},
        {"id": "REQ-003", "testable": True},
        {"id": "REQ-004", "testable": True},
        {"id": "REQ-005", "testable": True},
        {"id": "REQ-006", "testable": True},
        {"id": "REQ-007", "testable": True},
        {"id": "REQ-008", "testable": True},
        {"id": "REQ-009", "testable": True},
        {"id": "REQ-010", "testable": True},
        {"id": "REQ-011", "testable": True},
        {"id": "REQ-014", "testable": False},
    ]
    cases = [
        C(j, 1, "Notifications", "User opens notifications from the footer",
          LOGGED_IN, "1. Tap Notifications in the footer.",
          "Notification list is shown.",
          ["REQ-001"], "Access Notification section — footer", "Candidate", "positive"),
        C(j, 2, "Notifications", "User opens notifications from top icons",
          LOGGED_IN, "1. Tap the notifications top icon.",
          "Notification list is shown.",
          ["REQ-001"], "Access Notification section — top icons", "Candidate", "positive"),
        C(j, 3, "Notifications", "Notification types follow credentials and admin settings",
          "Accounts of different credentials; admin-configured types",
          "1. Open notifications on each account.",
          "User does not have access to all types. Types are Performance alerts, Stock request, Internal communication, according to admin portal settings.",
          ["REQ-002"], "Type of Notifications", "Manual", "other"),
        C(j, 4, "Notifications", "Internal communication is received in real time and kept in history",
          "Admin sends an internal communication (banner, text, image, or notification)",
          "1. Remain in the app. 2. Open notification historic.",
          "Internal communication is received in real time and appears in notification historic.",
          ["REQ-003"], "Internal communication", "Manual", "positive"),
        C(j, 5, "Notifications", "Notifications are in temporal order",
          "At least two notifications",
          "1. Open the list.",
          "Notifications are ordered temporally.",
          ["REQ-004"], "Order & Filter", "Candidate", "other", "Medium"),
        C(j, 6, "Notifications", "Historic is maintained for 7 days",
          "A notification older than 7 days and one within 7 days",
          "1. Open historic.",
          "Entries within 7 days remain. Entries older than 7 days are not kept.",
          ["REQ-005"], "Historic of notification should be maintained for 7 days", "Manual", "boundary", "Medium"),
        C(j, 7, "Notifications", "Type filter is available to reseller, reseller supervisor, and dealer",
          "Logged in as reseller, reseller supervisor, or dealer",
          "1. Open notifications. 2. Use type filter.",
          "User can filter by notification type.",
          ["REQ-006"], "Filters will only be accessible to reseller, reseller supervisor and dealer", "Manual", "positive", "Medium"),
        C(j, 8, "Notifications", "Type filter is not available to other profiles",
          "Logged in as a profile that is not reseller, reseller supervisor, or dealer",
          "1. Open notifications.",
          "Type filters are not accessible.",
          ["REQ-006"], "Filters will only be accessible to...", "Manual", "negative", "Medium"),
        C(j, 9, "Notifications", "List rows share the same format",
          "At least one notification of any type",
          "1. Observe list rows.",
          "Each row shows name, date, and description of the notification.",
          ["REQ-007"], "Listing of notifications", "Candidate", "positive"),
        C(j, 10, "Notifications", "Performance alerts have no details",
          "A Performance alert exists",
          "1. Open the Performance alert.",
          "No details are shown.",
          ["REQ-008"], "Details — Performance alerts", "Manual", "other", "Medium"),
        C(j, 11, "Notifications", "Internal communication details match admin content",
          "An internal communication notification exists",
          "1. Open it.",
          "Details are document, text, or other as defined by the admin.",
          ["REQ-009"], "Details — Internal communication", "Manual", "positive", "Medium"),
        C(j, 12, "Notifications", "Some notifications offer an action button",
          "A notification type that has an action",
          "1. Open the notification.",
          "An action button is available for some notifications. Which types is not fully listed beyond the details table.",
          ["REQ-010"], "Normal Course step 4", "Manual", "other", "Medium"),
        C(j, 13, "Notifications", "Use-case labels Registration through Reload are listed without expected UI mapping",
          LOGGED_IN, "1. Observe notifications related to the listed use cases if any exist.",
          "Ticket lists Registration, Upgrade Account, Upgrade KYC, SIM Swap, ReIdentification, Airtime, Bundles, Reload and says template will be shared later. No expected list mapping is stated.",
          ["REQ-011"], "Use cases list", "Manual", "other", "Low", blocked=True),
        C(j, 14, "Admin Portal", "Notification types are managed in the admin portal",
          "Admin Portal access",
          "1. Locate notification type settings.",
          "Not testable from the mobile app. Admin portal management is Yes with no steps.",
          ["REQ-014"], "Admin portal management", "Manual", "other", "Low"),
    ]
    return reqs, cases


def saa_915():
    j = "SAA-915"
    reqs = [
        {"id": "REQ-001", "testable": True},
        {"id": "REQ-002", "testable": True},
        {"id": "REQ-003", "testable": True},
        {"id": "REQ-004", "testable": True},
        {"id": "REQ-005", "testable": True},
        {"id": "REQ-006", "testable": True},
        {"id": "REQ-007", "testable": True},
        {"id": "REQ-008", "testable": True},
        {"id": "REQ-009", "testable": True},
        {"id": "REQ-010", "testable": True},
        {"id": "REQ-011", "testable": True},
        {"id": "REQ-012", "testable": True},
        {"id": "REQ-013", "testable": True},
        {"id": "REQ-014", "testable": True},
        {"id": "REQ-015", "testable": True},
        {"id": "REQ-016", "testable": True},
        {"id": "REQ-017", "testable": True},
        {"id": "REQ-018", "testable": True},
        {"id": "REQ-019", "testable": True},
    ]
    cases = [
        C(j, 1, "Activity History", "User opens transaction historic from top icons",
          LOGGED_IN, "1. Select activity historic from top icons.",
          "List of transaction historic is shown.",
          ["REQ-001"], "Transaction historic — top icons", "Candidate", "positive"),
        C(j, 2, "Activity History", "User sees only transaction types allowed by credentials",
          "Two profiles with different authorised transaction types",
          "1. Open historic on each profile.",
          "User according to their credentials will not have access to all type of Transaction. Types listed: Customer registration, Airtime & Bundle sales, Customer Services.",
          ["REQ-002", "REQ-005"], "Type of transactions", "Manual", "other"),
        C(j, 3, "Activity History", "Only current-day transactions from midnight to midnight",
          "A same-day transaction and a previous-day transaction",
          "1. Open historic.",
          "User views all transactions realised during the day. Historic is maintained for the current day only, starting and ending at midnight.",
          ["REQ-003", "REQ-007"], "current day only", "Manual", "boundary"),
        C(j, 4, "Activity History", "Historic is ordered temporally and can be filtered by type",
          "More than one type today",
          "1. Observe order. 2. Filter by type.",
          "Ordered temporally. User can filter through the type of transactions.",
          ["REQ-006", "REQ-008"], "Order & Filter", "Manual", "other", "Medium"),
        C(j, 5, "Activity History", "Client registration list row fields",
          "A same-day client registration",
          "1. Observe the list row.",
          "Shows Transaction ID, date and time, certification status (certified, on-going, rejected).",
          ["REQ-009"], "Listing — client registration", "Manual", "positive"),
        C(j, 6, "Activity History", "Airtime & bundle list row fields",
          "A same-day airtime or bundle sale",
          "1. Observe the list row.",
          "Shows date and time, customer MSISDN, airtime top-up/bundle purchase, transaction cost. Commission earned is not asserted: comment 2026-09-17 says commission amount is removed.",
          ["REQ-010"], "Listing — Airtime & bundle sales", "Manual", "positive"),
        C(j, 7, "Activity History", "Reload sent list row fields",
          "A same-day reload sent",
          "1. Observe the list row.",
          "Shows products & amount reloaded, time and date, cost, touchpoint name and MSISDN who received the reload.",
          ["REQ-011"], "Listing — Reload sent", "Manual", "positive"),
        C(j, 8, "Activity History", "Transaction details page fields",
          "Any same-day transaction",
          "1. Open the transaction.",
          "Shows transaction volume at the top, customer MSISDN except client registration, type, date and time, Transaction ID, colour-coded certification for registration (Certified / On-going / Reject), Need Help at the bottom.",
          ["REQ-012"], "Details of transaction", "Manual", "positive"),
        C(j, 9, "Activity History", "Rejected registration shows reason and Upgrade Customer File",
          "Rejected client registration today",
          "1. Open details.",
          "Rejection reason is shown. Upgrade customer file button redirects to the flow.",
          ["REQ-013"], "Reject — reason and upgrade button", "Manual", "positive"),
        C(j, 10, "Activity History", "Upgrade from historic is only for rejected files and pre-fills the number",
          "Rejected customer file in historic; agent authorised for upgrade",
          "1. Start Upgrade from details.",
          "User is redirected to AA-6.3 Check and Upgrade Customer Status. Only rejected files. Customer number is already populated and certification status is shown with required missing details.",
          ["REQ-014"], "Call for Actions", "Manual", "positive"),
        C(j, 11, "Commissions", "Commission display vs BO disable, superseded by comment",
          "Admin commission scheme on or off",
          "1. Open historic.",
          "Description says commission per transaction and total at the bottom, hidden if disabled from BO. Comment 2026-09-17: commission amount is removed. Assert commission is not shown.",
          ["REQ-015"], "Commissions + comment commission amount is removed", "Manual", "other", "Medium"),
        C(j, 12, "Performance card", "Performance card at the top of historic",
          LOGGED_IN, "1. Open activity historic.",
          "A performance card is at the top showing balance at beginning of day, generated revenue (sum of transaction costs, commissions not included), and balance end of day.",
          ["REQ-016", "REQ-017"], "Performance card", "Candidate", "positive"),
        C(j, 13, "Performance card", "KPI arrows vs yesterday or target",
          "KPI comparison data available",
          "1. Observe arrows on the historic performance card.",
          "Registration/Certification/Active Agents/Airtime sales/Reload/POS out of stock vs yesterday; Gross Add vs target. Greater: up green. Lower: down red. Equal: horizontal orange.",
          ["REQ-018", "REQ-019"], "Performance Success", "Manual", "other", "Medium"),
        C(j, 14, "Activity History", "Preconditions row says notifications; normal course says activity historic",
          LOGGED_IN, "1. Open activity historic from top icons, not notifications.",
          "Normal Course is used: activity historic from top icons. The Preconditions line that says notifications is treated as a copy error, not a second entry point.",
          ["REQ-001"], "Normal Course vs Preconditions", "Manual", "other", "Low"),
    ]
    return reqs, cases


def saa_917():
    j = "SAA-917"
    reqs = [
        {"id": "REQ-001", "testable": True},
        {"id": "REQ-002", "testable": True},
        {"id": "REQ-003", "testable": True},
        {"id": "REQ-004", "testable": True},
        {"id": "REQ-005", "testable": True},
        {"id": "REQ-006", "testable": True},
        {"id": "REQ-007", "testable": True},
        {"id": "REQ-008", "testable": True},
        {"id": "REQ-009", "testable": True},
        {"id": "REQ-010", "testable": True},
        {"id": "REQ-011", "testable": True},
        {"id": "REQ-012", "testable": True},
        {"id": "REQ-013", "testable": True},
        {"id": "REQ-014", "testable": True},
    ]
    cases = [
        C(j, 1, "KYC Form", "Form is used for registration and re-registration",
          LOGGED_IN, "1. Open Client Registration. 2. Open Re-identification if available.",
          "The KYC form in this annex applies to registration and re-registration.",
          ["REQ-001"], "This Form is For Registration and Re-Registration", "Candidate", "positive", "Medium"),
        C(j, 2, "KYC Form", "National ID is offered and OCR is mandatory",
          "On KYC ID type selection",
          "1. Select National ID. 2. Attempt to continue without OCR.",
          "National ID is available. OCR is mandatory.",
          ["REQ-002"], "Type of ID — National ID", "Manual", "positive"),
        C(j, 3, "KYC Form", "CEDEAO ID is offered and OCR is optional",
          "On KYC ID type selection",
          "1. Select CEDEAO / CEDAO. 2. Continue with OCR skipped if the UI allows.",
          "CEDEAO ID is available. OCR is optional.",
          ["REQ-003"], "CEDEAO ID", "Manual", "positive"),
        C(j, 4, "KYC Form", "Foreign passport is 8 digits and characters; OCR mandatory",
          "Foreign passport",
          "1. Select Passeport. 2. Enter an ID that is not 8 alphanumeric. 3. Scan with OCR.",
          "Passport is allowed except national. Length is 8 digits and character long. OCR is mandatory.",
          ["REQ-004"], "Passeport — except national, 8 digits and character long", "Manual", "boundary"),
        C(j, 5, "KYC Form", "Senegalese passport uses NIN; OCR mandatory",
          "Senegalese passport",
          "1. Select Passport - Senegalese.",
          "ID is NIN. OCR is mandatory.",
          ["REQ-005"], "Passport - Senegalese | NIN", "Manual", "positive"),
        C(j, 6, "KYC Form", "Refugee card is 11 digits and characters; OCR optional",
          "Refugee card",
          "1. Select Refugee card. 2. Enter a value that is not 11 alphanumeric.",
          "Refugee card is available. Length is 11 digits and character long. OCR is optional.",
          ["REQ-006"], "Refugee card", "Manual", "boundary"),
        C(j, 7, "KYC Form", "Customer picture is not required on this annex",
          "On KYC form",
          "1. Look for a mandatory customer picture capture on the form defined by this annex.",
          "Picture of client is No / NA. Do not treat SAA-910 Customer Photo as this annex's rule when they disagree; record the observed form.",
          ["REQ-007"], "Customer identification — Picture of client | No", "Manual", "other", "Medium"),
        C(j, 8, "KYC Form", "Fingerprint is not required",
          "On KYC form",
          "1. Look for fingerprint capture.",
          "Fingerprint is No / NA.",
          ["REQ-008"], "Fingerprint | No", "Manual", "other", "Medium"),
        C(j, 9, "KYC Form", "Name, last name, date of birth, address, ID number are mandatory with OCR YES",
          "On KYC form after scan",
          "1. Observe Name, Last name, Date of birth, Address, ID number. 2. Attempt to clear each.",
          "Those fields are mandatory. OCR column is YES.",
          ["REQ-009", "REQ-011", "REQ-013", "REQ-014"], "KYC Form mandatory OCR YES fields", "Manual", "positive"),
        C(j, 10, "KYC Form", "Gender is present and not mandatory",
          "On KYC form",
          "1. Leave Gender empty and continue.",
          "Gender is Yes, Not Mandatory. OCR optional.",
          ["REQ-010"], "Gender | Yes, Not Mandatory", "Manual", "negative", "Medium"),
        C(j, 11, "KYC Form", "Country is only for passport and OCR YES",
          "Passport selected, then National ID selected",
          "1. Observe Country on passport. 2. Observe Country on National ID.",
          "Country is only for passport.",
          ["REQ-012"], "Country | Only for passport", "Manual", "other", "Medium"),
        C(j, 12, "KYC Form", "Address captures street, region, préfecture, commune, canton, city",
          "On address entry",
          "1. Observe address elements.",
          "Address (street, region, préfecture, commune, canton, city) is mandatory.",
          ["REQ-013"], "Adress (street, region, préfecture, commune, canton, city)", "Manual", "positive", "Medium"),
    ]
    return reqs, cases
